#!/usr/bin/env python3

voices = {
        "Naja": "Danish (F) - Naja",
        "Mads": "Danish (M) - Mads",
        "Lotte": "Dutch (F) - Lotte",
        "Ruben": "Dutch (M) - Ruben",
        "Nicole": "English, Australian (F) - Nicole",
        "Russell": "English, Australian (M) - Russell",
        "Amy": "English, British (F) - Amy",
        "Emma": "English, British (F) - Emma",
        "Brian": "English, British (M) - Brian",
        "Raveena": "English, Indian (F) - Raveena",
        "Aditi": "English, Indian (F) - Aditi",
        "Ivy": "English, US (F) - Ivy",
        "Joanna": "English, US (F) - Joanna",
        "Kendra": "English, US (F) - Kendra",
        "Kimberly": "English, US (F) - Kimberly",
        "Salli": "English, US (F) - Salli",
        "Joey": "English, US (M) - Joey",
        "Justin": "English, US (M) - Justin",
        "Matthew": "English, US (M) - Matthew",
        "Geraint": "English, Welsh (M) - Geraint",
        "Celine": "French (F) - Céline",
        "Lea": "French (F) - Léa",
        "Mathieu": "French (M) - Mathieu",
        "Chantal": "French, Canadian (F) - Chantal",
        "Marlene": "German (F) - Marlene",
        "Vicki": "German (F) - Vicki",
        "Hans": "German (M) - Hans",
        "Dóra": "Icelandic (F) - Dóra",
        "Karl": "Icelandic (M) - Karl",
        "Carla": "Italian (F) - Carla",
        "Giorgio": "Italian (M) - Giorgio",
        "Takumi": "Japanese (M) - Takumi",
        "Mizuki": "Japanese (F) - Mizuki",
        "Seoyeon": "Korean (F) - Seoyeon",
        "Liv": "Norwegian (F) - Liv",
        "Ewa": "Polish (F) - Ewa",
        "Maja": "Polish (F) - Maja",
        "Jacek": "Polish (M) - Jacek",
        "Jan": "Polish (M) - Jan",
        "Vitoria": "Portugese, Brazilian (F) - Vitória",
        "Ricardo": "Portugese, Brazilian (M) - Ricardo",
        "Ines": "Portugese, European (F) - Inês",
        "Cristiano": "Portugese, European (M) - Cristiano",
        "Carmen": "Romanian (F) - Carmen",
        "Tatyana": "Russian (F) - Tatyana",
        "Maxim": "Russian (M) - Maxim",
        "Conchita": "Spanish, European (F) - Conchita",
        "Enrique": "Spanish, European (M) - Enrique",
        "Penélope": "Spanish, US (F) - Penélope",
        "Miguel": "Spanish, US (M) - Miguel",
        "Astrid": "Swedish (F) - Astrid",
        "Filiz": "Turkish (F) - Filiz",
        "Gwyneth": "Welsh (F) - Gwyneth",
        }

sounds = {
          'Air Horn 1': '/alarms/air_horns/air_horn_01',
          'Boing 1': '/alarms/beeps_and_bloops/boing_01',
          'Bell 1': '/alarms/beeps_and_bloops/bell_01',
          'Bell 2': '/alarms/beeps_and_bloops/bell_02',
          'Bell 3': '/alarms/chimes_and_bells/chimes_bells_05',
          'Buzzer 1': '/alarms/buzzers/buzzers_01',
          'Buzzer 2': '/alarms/buzzers/buzzers_04',
          'Chimes': '/alarms/chimes_and_bells/chimes_bells_04',
          'Ding 1': '/alarms/beeps_and_bloops/bell_03',
          'Ding 2': '/alarms/beeps_and_bloops/bell_04',
          'Doorbell 1': '/home/amzn_sfx_doorbell_01',
          'Doorbell 2': '/home/amzn_sfx_doorbell_chime_02',
          'Electronic Beep 1': '/musical/amzn_sfx_electronic_beep_01',
          'Electronic Beep 2': '/musical/amzn_sfx_electronic_beep_02',
          'Electronic Beep 3': '/scifi/amzn_sfx_scifi_timer_beep_01',
          'Intro 1': '/alarms/beeps_and_bloops/intro_02',
          'Siren 1': '/scifi/amzn_sfx_scifi_alarm_01',
          'Siren 2': '/alarms/beeps_and_bloops/buzz_03',
          'Tone 1': '/musical/amzn_sfx_test_tone_01',
          'Tone 2': '/alarms/beeps_and_bloops/tone_02',
          'Tone 3': '/alarms/beeps_and_bloops/tone_05',
          'Woosh': '/alarms/beeps_and_bloops/woosh_02',
        }
